### ISSUE TITLE
[BUG REPORT] Not all members of the github repo can run update_wiki and update_models flows

### ISSUE THREAD

**Issue by PierreLamusse** [edamametechnologies/threatmodels#55]
update_models:
```
Run actions-js/push@master
Started: bash /home/runner/work/_actions/actions-js/push/master/start.sh
Push to branch dev
[dev ea3fe3b] chore: autopublish 2024-04-03T06:34:55Z
 1 file changed, 3 insertions(+), 3 deletions(-)
remote: Permission to edamametechnologies/threatmodels.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/edamametechnologies/threatmodels.git/': The requested URL returned error: 403
Error: Invalid status code: [12](https://github.com/edamametechnologies/threatmodels/actions/runs/8534300268/job/23378440525#step:9:13)8
    at ChildProcess.<anonymous> (/home/runner/work/_actions/actions-js/push/master/start.js:9:19)
    at ChildProcess.emit (node:events:5[13](https://github.com/edamametechnologies/threatmodels/actions/runs/8534300268/job/23378440525#step:9:14):28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/actions-js/push/master/start.js:9:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:[16](https://github.com/edamametechnologies/threatmodels/actions/runs/8534300268/job/23378440525#step:9:17))
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
    ```

**Comment by PierreLamusse** [comment]
Closed by the commit "REFACTOR: wiki update" : "83c0074aaf8bec68ac95927ab30e73f5a7622510"
